DROP TABLE EMPLOYEE_TABLE;

CREATE TABLE EMPLOYEE_TABLE(
    EMPNO NUMBER(6),
    ENAME VARCHAR(20),
    JOB VARCHAR(20),
    SAL NUMBER(6) NOT NULL,
    DEPTNO NUMBER(2) DEFAULT 10,
    CONSTRAINT EMP_NO_PK PRIMARY KEY(EMPNO),
    CONSTRAINT EMP_ENAME_UK UNIQUE(ENAME),
    CONSTRAINT EMP_JOB_CHK CHECK (JOB IN ('Prof', 'AP', 'Lect'))
);

DESC EMPLOYEE_TABLE;

SELECT CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMPLOYEE_TABLE';

INSERT INTO EMPLOYEE_TABLE VALUES(
    1,
    'Shourya',
    'SRE',
    1000,
    10
);

INSERT INTO EMPLOYEE_TABLE VALUES(
    1,
    'Amit',
    'Prof',
    1000,
    1
);

INSERT INTO EMPLOYEE_TABLE VALUES(
    1,
    'Aditya',
    'Prof',
    1000,
    1
);

INSERT INTO EMPLOYEE_TABLE VALUES(
    2,
    'Aditya',
    'Prof',
    NULL,
    1
);

INSERT INTO EMPLOYEE_TABLE(
    EMPNO,
    ENAME,
    JOB,
    SAL
) VALUES(
    2,
    'Shourya',
    'Prof',
    1000
);

SELECT *
FROM EMPLOYEE_TABLE;

DROP TABLE SP;

DROP TABLE S;

DROP TABLE P;

CREATE TABLE S(
    SNO INT,
    SNAME VARCHAR(20),
    CITY VARCHAR(20),
    CONSTRAINT S_SNO_PK PRIMARY KEY(SNO)
);

CREATE TABLE P(
    PNO INT,
    PNAME VARCHAR(20),
    COLOR VARCHAR(10),
    CONSTRAINT P_PNO_PK PRIMARY KEY(PNO)
);

CREATE TABLE SP(
    SNO INT,
    PNO INT,
    QTY NUMBER(5),
    CONSTRAINT SP_SNO_FK FOREIGN KEY(SNO) REFERENCES S(SNO),
    CONSTRAINT SP_PNO_FK FOREIGN KEY(PNO) REFERENCES P(PNO),
    CONSTRAINT SP_SNOPNO_PK PRIMARY KEY(SNO, PNO)
);

CREATE TABLE SA(
    SNO INT PRIMARY KEY,
    SNAME VARCHAR(20),
    CITY VARCHAR(20)
);

DROP TABLE SA;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'P';

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'S';

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'SP';

-- Create table dept which has the following attributes
-- (department table)
-- (deptno, dname)
-- Where deptno is primary key, dname in (Acc, comp, elect)
CREATE TABLE DEPT(
    DEPTNO INT,
    DNAME VARCHAR(20),
    CONSTRAINT DEPT_DEPTNO_PK PRIMARY KEY(DEPTNO),
    CONSTRAINT DEPT_DNAME_CHK CHECK (DNAME IN ('Acc', 'comp', 'elect'))
);

-- Create table emp which has the following attributes (employee
-- table)
-- (@empno, ename, job, sal, deptno)
-- Where empno is primary key, ename is unique, job in (Prof, AP,
-- and Lect), sal is not NULL, and deptno is foreign key

DROP TABLE EMP;

CREATE TABLE EMP(
    EMPNO NUMBER(3),
    ENAME VARCHAR(20),
    JOB VARCHAR(20),
    SAL NUMBER(5) NOT NULL,
    DEPTNO INT,
    CONSTRAINT EMP_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO),
    CONSTRAINT EMP_EMPNO_PK PRIMARY KEY(EMPNO),
    CONSTRAINT EMP_JOB_CHK CHECK (JOB IN ('Prof', 'AP', 'Lect')),
    CONSTRAINT EMP_ENAME_UK UNIQUE(ENAME)
);

-- DROP TABLE EMPLOYEE_TABLE;

-- DROP TABLE SP;

-- DROP TABLE S;

-- DROP TABLE P;

-- DROP TABLE EMP;

-- DROP TABLE DEPT;

CREATE TABLE BOOK(
    RNO NUMBER(2),
    DOI DATE,
    DOR DATE,
    CONSTRAINT BK_D_CHK CHECK(DOR>DOI),
    CONSTRAINT BK_RNO_PK PRIMARY KEY(RNO)
);

INSERT INTO BOOK VALUES(
    1,
    TO_DATE('07-02-2022', 'DD-MM-YYYY'),
    TO_DATE('05-02-2022', 'DD-MM-YYYY')
);

DROP TABLE BOOK;

CREATE TABLE ST(
    RNO NUMBER(2),
    CLASS CHAR,
    MARKS NUMBER(2),
    CONSTRAINT ST_MARKS_CHK CHECK(MARKS>0),
    CONSTRAINT ST_RNO_PK PRIMARY KEY(RNO)
);

INSERT INTO ST VALUES(
    1,
    'X',
    -9
);

DROP TABLE ST;